### ISSUE TITLE
push the codeCov report as a comment to a pull request

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/abapCov#10]
Something like that: https://github.com/miyakogi/pyppeteer/pull/227#issuecomment-498782123
Don't know if it's somehow possible 😄

**Comment by larshp** [comment]
its possible

for open source:
* the ABAP dev edtions cannot be put online on the internet providing services due to licensing
* if its done on a fixed system, the code in pull requests are untrusted, so I'd probably not run it in a fixed system
* that leaves spawning systems, I personally dont have the $ to spawn 32gb+ systems for each pull request/push

so, the way forward is to run the unit tests via the transpiler instead

**Comment by JohannesKonings** [comment]
Thanks, so I'll try it with the transpiler.
